name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Update References
        run: bash tools/deploy.sh

      - name: Deploy to GitHub Pages
        if: success()
        uses: qoomon/deploy-to-github-pages-action@v1
        with:
          GITHUB_PAGES_SOURCE_DIR: ./
          GITHUB_PAGES_BRANCH: gh-pages
          GITHUB_PAGES_REPLACE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
